### ISSUE TITLE
vocab

### ISSUE THREAD

**Issue by zihanlizi** [JJASMINE22/LeakGan#1]
‘C:\\PythonProjects\\LeakGan\\vocab\\image_coco.json'请问这个文件是什么，应该在哪里找

**Comment by JJASMINE22** [comment]
> ‘C:\PythonProjects\LeakGan\vocab\image_coco.json'请问这个文件是什么，应该在哪里找

该路径保存数据集的分词字典，由utils/generate.py生成，可以根据config.py修改具体路径

**Comment by zihanlizi** [comment]
谢谢 : )

**Comment by zihanlizi** [comment]
And 我也是xhu的！太巧了

**Comment by JJASMINE22** [comment]
> 

加油！

**Comment by JJASMINE22** [comment]
> And 我也是xhu的！太巧了

加油！
